name: 'Jest badges generation action'
description: 'Action generating jest coverage badges and pushing them to the repo'

inputs:
  branches:
    description: 'Branches on which the badges should be generated. Commas separated.'
    default: 'master,main'
  coverage-summary-path:
    description: 'Jest coverage summary path (json-summary). Defining this may be useful if you need to run this action on a monorepo.'
    default: './coverage/coverage-summary.json'
  commit-message:
    description: 'Commit message of the commit with generated badges.'
    default: 'Updating coverage badges'

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: check-square
  color: green
